### PR TITLE
Completed MystryChallange.cpp

### PR DESCRIPTION
**Pull request by Jayshah6699**
Check different cpp solution.

### CODE REVIEW

**Comment by Jayshah6699** [comment]
@aayushi-droid kindly assign me the task

**Comment by Jayshah6699** [comment]
@aayushi-droid Kindly assign me the task MystryChallage.cpp

**Comment by aayushi-droid** [comment]
Mystry Challanged Task already assigned.

**Comment by aayushi-droid** [comment]
Valid Pull Request for HacktoberFest will Count from 1 October to 31 October. @Jayshah6699

**Pull request closed without merging**
