### PR TITLE
Successfully Updated alternative

### LINKED ISSUE #41: Phone Letter Combination
Before jumping into Pr first comment for assign.

**Problem statement** :Phone Letter Combination
**Probelm Link** : https://edabit.com/challenge/npLurjMJofmFRCJwx
**Choose one Cateorgy** -  Expert 
**question category** : Algorithms, Arrays, logic, Loops

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. 
 * Problem Link : https://edabit.com/challenge/npLurjMJofmFRCJwx
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

### PR DESCRIPTION
**Pull request by Manoj13-coder**
## Description

enter here if you have any details

**Program Name** -       
**Issue No.**- #41 
> Type issue number after hash(#)

## Checklist(self check)

- [x] Yes, this task assigned to me.
- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My Filename is in camelCase format
- [x] I have added **Problem statement**, **Problem link** in file.

### CODE REVIEW

**Comment by aayushi-droid** [comment]
Please Take Care Of Naming conventions for this Repo. we are using camelcase here.
Rename your file to phoneLetterCombinationAlternative.cpp

**Comment by Manoj13-coder** [comment]
ok i will do it sorry for that

**Comment by Manoj13-coder** [comment]
Done !!!

**Comment by aayushi-droid** [comment]
- [x]  - Task Complete 
Issue no. - #41

**Pull request merged**
