### PR TITLE
Making a Box

### LINKED ISSUE #184: Making a Box
Before jumping into Pr first comment for assign.

**Problem statement** :  Create a function that creates a box based on dimension n.
**Probelm Link** :  https://edabit.com/challenge/yHeTBuJ6LDw3nhA7k
**Choose one Cateorgy** - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
**question category** :  Hard

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

### PR DESCRIPTION
**Pull request by mauryahimanshu**
## Description

enter here if you have any details

**Program Name** -  Making A Box
**Issue No.**- #184 

## Checklist(self check)

- [ ] Yes, this task assigned to me.
- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My Filename is in camelCase format
- [x] I have added **Problem statement**, **Problem link** in file.

### CODE REVIEW

**Comment by aayushi-droid** [comment]
@mauryahimanshu Why there is 3 file ?

**Review by mauryahimanshu — COMMENTED** [review]
The solution is correct.

**Comment by aayushi-droid** [comment]
solution is correct but GCD LCM and count letter was assigned to you?
I have see only making a box

**Comment by mauryahimanshu** [comment]
No GCD LCM was not assigned to me.

**Comment by mauryahimanshu** [comment]
Count letter Issue was created by me.

**Comment by aayushi-droid** [comment]
then delete LCM and GCD file... and commit
then I will merge

**Comment by mauryahimanshu** [comment]
OK

**Comment by aayushi-droid** [comment]
Thanks @mauryahimanshu  for making contribution.

**Pull request merged**
