### PR TITLE
Phone Letter Combination

### LINKED ISSUE #41: Phone Letter Combination
Before jumping into Pr first comment for assign.

**Problem statement** :Phone Letter Combination
**Probelm Link** : https://edabit.com/challenge/npLurjMJofmFRCJwx
**Choose one Cateorgy** -  Expert 
**question category** : Algorithms, Arrays, logic, Loops

---
Before submitting a PR please Check some details.

- [x] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [x]  Choose label for Problem , example- "good first issue", "easy"
- [x]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. 
 * Problem Link : https://edabit.com/challenge/npLurjMJofmFRCJwx
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

### PR DESCRIPTION
**Pull request by Jayshah6699**
## Description

Before jumping into Pr first comment for assign.

Problem statement : Phone Letter Combinations
Probelm Link : https://edabit.com/challenge/npLurjMJofmFRCJwx
Choose one Cateorgy - Expert
question category : Algoritms, Arrays, Loops
**Issue No.**- #
> Type issue number after hash(#)

## Checklist

- [x] Yes, this task assigned to me.
- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My Filename is in camelCase format
- [x] I have added **Problem statement**, **Problem link** in file.

### CODE REVIEW

**Comment by Jayshah6699** [comment]
@aayushi-droid completed the task check

**Comment by aayushi-droid** [comment]
You have to assign an issue before making pull request. please make an issue for the same problem. then add only one solution.
you are adding multiple files that's are not even assigned to you.

Make an issue to phoneLetterCombination in issue section.

**Comment by Jayshah6699** [comment]
I have deleted except one file

**Comment by Jayshah6699** [comment]
ok

**Comment by Jayshah6699** [comment]
created the issue.
check

**Comment by Jayshah6699** [comment]
@aayushi-droid I have created the issue.

**Comment by aayushi-droid** [comment]
- [x] Task Complete

**Pull request merged**
